SELECT C.APNT_NO, C.PT_NAME, C.PT_NO, C.MCDP_CD, D.DR_NAME, C.APNT_YMD
FROM (
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, A.APNT_YMD, A.MDDR_ID
FROM APPOINTMENT AS A JOIN PATIENT AS P
ON A.PT_NO = P.PT_NO
WHERE MCDP_CD = "CS" AND (DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND APNT_CNCL_YN = "N")) AS C JOIN
(SELECT DR_ID, DR_NAME
FROM DOCTOR) AS D
ON C.MDDR_ID = D.DR_ID
ORDER BY C.APNT_YMD
