SELECT B.CATEGORY, SUM(C.SALES) AS TOTAL_SALES
FROM BOOK as B JOIN BOOK_SALES AS C
ON B.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE BETWEEN DATE("2022-01-01") AND DATE("2022-01-31")
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY