SELECT S.AUTHOR_ID, S.AUTHOR_NAME, S.CATEGORY, SUM(F.SALES * S.PRICE) AS TOTAL_SALES
FROM (SELECT *
FROM BOOK_SALES
WHERE SALES_DATE >= "2022-01-01" AND SALES_DATE <= "2022-01-31"
) AS F JOIN (SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.BOOK_ID, B.PRICE
FROM BOOK AS B JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
) AS S
ON F.BOOK_ID = S.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
